import { describe, expect, it } from 'vitest';
import { pendingScripts, scriptKey } from '../src/editor/canvas/scripts.js';
import type { ComponentDefinition } from '../src/types.js';
import { componentsModuleSource, islandWrapperSource } from '../src/vite.js';

const counter: ComponentDefinition = {
	type: 'counter',
	label: 'Counter',
	component: './src/Counter.tsx',
	client: 'visible',
};

describe('island wrappers', () => {
	it('statically import the component with a literal client directive', () => {
		expect(islandWrapperSource(counter, '/site/src/Counter.tsx')).toBe(
			[
				'---',
				`// Generated by Tapestry for "counter" (client:visible). Don't edit: it's rewritten on start.`,
				'import Component from "/site/src/Counter.tsx";',
				'---',
				'<Component client:visible {...Astro.props} />',
				'',
			].join('\n'),
		);
	});

	it('pass children and named slots through', () => {
		const source = islandWrapperSource(
			{ ...counter, client: 'idle', acceptsChildren: true, slots: { aside: { label: 'Aside' } } },
			'/site/src/Counter.tsx',
		);
		expect(source).toContain(
			'<Component client:idle {...Astro.props}><slot /><slot name="aside" slot="aside" /></Component>',
		);
	});

	it('escape the import path and refuse components without a directive', () => {
		expect(islandWrapperSource(counter, '/we"ird/C.tsx')).toContain('import Component from "/we\\"ird/C.tsx";');
		expect(() => islandWrapperSource({ ...counter, client: undefined }, '/x.tsx')).toThrow();
	});

	it('the components module imports the wrapper instead of the component', () => {
		const source = componentsModuleSource(
			[counter],
			new URL('file:///site/'),
			new Map([['counter', '/site/w/counter.astro']]),
		);
		expect(source).toContain('import C0 from "/site/w/counter.astro";');
		expect(source).not.toContain('Counter.tsx');
	});
});

type FakeScript = { getAttribute: (name: string) => string | null; textContent: string };
const script = (attrs: Record<string, string>, text = ''): FakeScript => ({
	getAttribute: (name) => attrs[name] ?? null,
	textContent: text,
});
const base = 'http://site.test/page';

describe('canvas scripts', () => {
	it('identify scripts by URL or inline source; ignore data and empty scripts', () => {
		const key = (s: FakeScript) => scriptKey(s as unknown as HTMLScriptElement, base);
		expect(key(script({ type: 'module', src: '/a.js' }))).toBe('src:module:http://site.test/a.js');
		expect(key(script({ src: 'b.js' }))).toBe('src:classic:http://site.test/b.js');
		expect(key(script({}, 'run()'))).toBe('inline:classic:run()');
		expect(key(script({ type: 'application/ld+json' }, '{}'))).toBeNull();
		expect(key(script({ type: 'text/plain' }, 'x'))).toBeNull();
		expect(key(script({}, '  '))).toBeNull();
	});

	it('only scripts not run yet, once each, in order', () => {
		const scripts = [
			script({}, 'bootstrap()'),
			script({ type: 'module', src: '/island.js' }),
			script({}, 'bootstrap()'),
			script({ type: 'module', src: '/vite-client.js' }),
		];
		const response = { querySelectorAll: () => scripts } as unknown as Document;
		const ran = new Set(['src:module:http://site.test/vite-client.js']);
		expect(pendingScripts(response, base, ran)).toEqual([scripts[0], scripts[1]]);
	});
});
